### ISSUE TITLE
Cauldron namespace is not available in lib

### ISSUE THREAD

**Issue by dequejosie** [dequelabs/cauldron#428] opened 2021-11-17 17:58 UTC
We declare namespace `Cauldron` in `global.d.ts` in `packages/react/src`. Although Cauldron builds find, but the namesapce is not available for components in `lib`. It seems that this is an issue with Cauldron 3.0.

<img width="552" alt="Screen Shot 2021-11-17 at 12 55 55 PM" src="https://user-images.githubusercontent.com/83524297/142255718-3a4273e7-d11c-4a54-8d79-bb16fe75e659.png">

The error is `Cannot find namespace 'Cauldron'`.

There might be something wrong with the build process:

```
  "scripts": {
    "build": "yarn build:lib && yarn build:css",
    "prebuild:lib": "node scripts/buildIconTypes.js",
    "build:lib": "rollup -c && tsc --declaration --emitDeclarationOnly --outDir lib",
    "build:css": "postcss --output=lib/cauldron.css src/index.css",
    "dev": "concurrently 'yarn build:css --watch' 'rollup -c --watch'",
    "prepublishOnly": "NODE_ENV=production yarn build",
    "test": "jest --maxWorkers=1 --coverage"
  },
```

**Comment by stephenmathieson** [comment] 2021-11-17 20:50
This is due to the TypeScript compiler not re-emitting `.d.ts` files.

**Comment by Keerthi-Penukonda** [comment] 2021-11-18 05:02
@dequejosie is it testable by QA?

**Comment by Keerthi-Penukonda** [comment] 2021-11-20 06:58
@dequejosie verified this ticket and confirmed that it is working fine. Hence closing the ticket.

**Closed by Keerthi-Penukonda** 2021-11-20 06:58 UTC
Labels: bug
