### ISSUE TITLE
Set id as a required for checkbox, or use a default

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/cauldron#841] opened 2022-12-19 13:59 UTC
The following results in a checkbox that does't have an accessible name:

```jsx
() => <Checkbox label="Hello world" />
```

The `id` property isn't required, but then when left out, no alternative way of adding an accessible name is used. There are lots of ways this can be solved. Like require the ID, use a randomised ID, or use `aria-label` to add an accessible name.

**Comment by scurker** [comment] 2023-02-17 20:10
Duplicate of #71

**Closed by scurker** 2023-02-17 20:10 UTC
