### ISSUE TITLE
Page title is not updated when navigating directly to a component page

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#787] opened 2022-09-20 20:55 UTC
![image](https://user-images.githubusercontent.com/3180185/191362233-a4cf7cdb-dd4d-48ae-9505-7afcf512bd49.png)

can reproduce by navigating directly to a component page, like https://cauldron.dequelabs.com/components/Checkbox for example...OR the user right-clicks on any navigational link and opens the page in a new window

In [docs/index.js](https://github.com/dequelabs/cauldron/blob/develop/docs/index.js), we use the [react-helmet](https://www.npmjs.com/package/react-helmet) to dynamically update the page title.

**Comment by tbusillo** [comment] 2022-10-08 20:05
I believe the fix here is to redirect all requests to `/*` and [rewrite them as 200s in Amplify](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html). 

This happens due to the server seeing the request/responding to it/handling it before React Router can pick it up and take over routing. If you were to ping the routes and check the status of requests outside of `/` right now, they are throwing a 404 underneath. 

Even with the 404, React Router eventually gets hit with the request regardless since it is still the index of the base path. But, React Router now thinks the request came to the base path (which it kinda did), so it's showing the title, meta tags, etc. for it. 

Aside from the accessibility issues caused by this, it's really bad for SEO purposes, as crawlers can/do consider the link dead/broken.

**Comment by nikolaps17** [comment] 2022-10-14 15:58
Hello, Can you assign this issue to me? I will try to fix it.

**Closed** 2023-02-02 23:36 UTC
Labels: accessibility, audit, Hacktoberfest
