### ISSUE TITLE
remove default card (no longer used)

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#411] opened 2021-11-09 20:16 UTC
<img width="504" alt="Screen Shot 2021-11-09 at 12 16 17 PM" src="https://user-images.githubusercontent.com/3180185/140997997-22479736-2b45-4913-a539-1ea2e300d6df.png">

**Comment by scurker** [comment] 2023-02-22 18:46
duplicate of #712

**Closed by scurker** 2023-02-22 18:46 UTC
Labels: breaking
